name: stagexl_particle
version: 1.0.0
description: The particle emitter runtime for the StageXL library.
publish_to: none

environment:
  sdk: ^3.5.0
dependencies:
  stagexl:
    git: 
      url: https://github.com/mnordine/StageXL
      ref: package-web
  web: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any
